### ISSUE TITLE
Clock Drift

### ISSUE THREAD

**Issue by calvin-evans** [aws-samples/amazon-transcribe-websocket-static#10]
Hi, 

When trying to get a presigned URL using this example on a system with an incorrect time you get an invalid signature error. It looks like this is something the `correctClockSkew` option would usually handle in the SDK. Do you happen to have some pseudo-code that would aid in manually implementing similar functionality?

**Comment by brandonmwest** [comment]
hi Calvin, here's relevant code from the SDK that handles this. Hope it helps https://github.com/aws/aws-sdk-js/pull/706/commits/48012a46b311dcba8fdf9c12494b1cfc3f1ef2cf
