### ISSUE TITLE
Store audio file into S3.

### ISSUE THREAD

**Issue by balavenkatesh3322** [aws-samples/amazon-transcribe-websocket-static#11]
While live transcribe can we also store the audio files into S3 simultaneously? If yes, can you please point out where we need to configure bucket details in this library.

**Comment by brandonmwest** [comment]
That sounds like a better case for the regular transcription API rather than streaming ornuaing websockets, because you could record the audio file, push it to s3, and use a lambda function to Transcribe it. Either way, it's outside the scope of this demo.
