### ISSUE TITLE
Does it support React Native?

### ISSUE THREAD

**Issue by ykcadcg** [aws-samples/amazon-transcribe-websocket-static#12]
RN says it supports WebSocket https://facebook.github.io/react-native/docs/network.html, but I'm not sure if it works smoothly with your sample here. Any pitfalls to note? Thanks!

**Comment by brandonmwest** [comment]
I don't know React Native at all so I'm not sure, but it looks like it should be pretty straightforward, just point your websocket connection to a pre-signed URL.
