### ISSUE TITLE
Request has expired

### ISSUE THREAD

**Issue by andreesteva** [aws-samples/amazon-transcribe-websocket-static#15]
The moment I run the transcription demo, I get the following error: 
`Request has expired`
Please advise?

**Comment by chaschev** [comment]
That problem still exists

**Comment by brandonmwest** [comment]
This means you have a problem with your account or connection to AWS or potential an issue with audio encoding  Please confirm your connection, and then post enough information to debug the error, e.g. network traffic, browser console logs, erc

**Comment by chaschev** [comment]
I don't know. A competitor has a better connection
