### ISSUE TITLE
Access to Transcription Job

### ISSUE THREAD

**Issue by ffernandomaximo** [aws-samples/amazon-transcribe-websocket-static#16]
Hi,

How can I access the transcription job or JSON file generated by real time transcribe?
It is not stored in my amazon transcribe service (aws console).

Thanks in Advance

**Comment by brandonmwest** [comment]
There is no job because it is real-time. Everything is sent over the websocket. Check out the Network tab in your browser's dev tools and you can see the messages. You could stream the responses somewhere or implement logging from the client however you see fit.
