### ISSUE TITLE
Record Audio files too

### ISSUE THREAD

**Issue by ManishTiwari-cloud** [aws-samples/amazon-transcribe-websocket-static#17]
Can I get recorded audio too using this?

Actually I want to build an application where we will provide the paragraph to speak for the user and we are going to record the audio of user and extract the text from that audio and match extracted data with our paragraph to check accuracy.

So will I get the recorded audio of user along with text?

**Comment by brandonmwest** [comment]
Hi there, this outside the scope of this demo, but you could take the audio stream and stream it to disk as well as the websocket. If you want to use recorded audio, consider whether the non-streaming version of Amazon Transcribe might be better for your app.
