### ISSUE TITLE
"Error in connection establishment: net::ERR_NAME_NOT_RESOLVED" for new servers

### ISSUE THREAD

**Issue by e-rasvet** [aws-samples/amazon-transcribe-websocket-static#26]
Hello!

When I try to change servers list and add new server to the list I see this error in console:
"Error in connection establishment: net::ERR_NAME_NOT_RESOLVED"
ap-northeast-1  - Tokyo for example.

Why it is happen? Looks like user, which was created, should have access to all regions.

**Comment by brandonmwest** [comment]
Hi there, Amazon Transcribe Streaming is not yet available in Tokyo. Closest region is ap-southeast-2 Sydney. https://docs.aws.amazon.com/general/latest/gr/transcribe.html#transcribe_region
