### ISSUE TITLE
not working on mobile browsers

### ISSUE THREAD

**Issue by s0hel** [aws-samples/amazon-transcribe-websocket-static#7]
this is working great on desktop browsers, but how can we get the mic access on a mobile browser?i tried it on ios and it did not work

**Comment by brandonmwest** [comment]
I am not sure about iOS and don't have one to test with. It works on chrome
on my Android phone. Check Settings -> Privacy -> Microphone.

**Comment by brandonmwest** [comment]
I was finally able to test on iOS and it worked fine for me. I was able to grant access to the microphone in Safari as expected.
<img width="1194" alt="8FF10DDE-CB68-41B6-82EB-A7078E3E0929" src="https://user-images.githubusercontent.com/433682/66446293-cce47500-e9fe-11e9-9e7b-ac4994902f28.png">
